--Î∞õÏ? Î©îÏÑ∏Ïß??óê?Ñú OPT Í≤??Éâ?ïòÍ∏?
SELECT * 
FROM 
(
    SELECT ROWNUM RNUM, T.* FROM
        (
            SELECT * 
            FROM MEMBER M
            JOIN LETTER L ON (M.MEMBER_NO = L.SEND_MEMBER_NO)
            WHERE L.STATUS = 'O' AND M.MEMBER_ID LIKE '%'||?||'%' ORDER BY M.MEMBER_NO DESC
        ) T
)
WHERE RNUM BETWEEN ? AND ?;

--Í∑∏ÎÉ• Í≤??Éâ
SELECT * 
FROM 
    ( 
        SELECT ROWNUM RNUM , T.* 
        FROM
        ( 
            SELECT L.LETTER_NO , L.LETTER_TITLE , L.LETTER_CONTENT , L.SEND_MEMBER_NO , L.ENROLL_DATE , L.STATUS , M.MEMBER_NICK
            FROM LETTER L
            JOIN MEMBER M ON(L.SEND_MEMBER_NO = M.MEMBER_NO)
            WHERE L.STATUS = 'O' ORDER BY MEMBER_NO DESC
        )T 
    )
    WHERE RNUM BETWEEN ? AND ?;


--Î©îÏÑ∏Ïß? Ï¥? Í∞úÏàò
SELECT COUNT(*)
FROM ( 
        SELECT L.LETTER_NO , L.LETTER_TITLE , L.LETTER_CONTENT , L.SEND_MEMBER_NO , L.ENROLL_DATE , L.STATUS , M.MEMBER_NICK
        FROM LETTER L
        JOIN MEMBER M ON(L.SEND_MEMBER_NO = M.MEMBER_NO)
    )
WHERE STATUS = 'O';

select * from letter;


INSERT INTO 
LETTER (LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, STATUS)
VALUES (SEQ_LETTER_NO.NEXTVAL, (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = 'Ω…≈ıøÎ'), (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = 'Ω…ø¯øÎ'),'≈◊Ω∫∆Æ', '≈◊Ω∫∆Æ', 'O');

INSERT INTO 
LETTER (LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, STATUS)
VALUES (SEQ_LETTER_NO.NEXTVAL, (SELECT MEMBER_NO 
FROM (SELECT MEMBER_NO, ROW_NUMBER() OVER(ORDER BY ROWNUM ASC) AS RN 
FROM MEMBER WHERE MEMBER_NICK = ?) WHERE RN = 1), (SELECT MEMBER_NO 
FROM (SELECT MEMBER_NO, ROW_NUMBER() OVER(ORDER BY ROWNUM ASC) AS RN 
FROM MEMBER WHERE MEMBER_NICK = ?) WHERE RN = 1), ?, ?, 'O');

SELECT *
FROM ( SELECT ROWNUM RNUM, T.*
       FROM ( SELECT L.LETTER_NO, L.LETTER_TITLE, L.LETTER_CONTENT, L.RECEIVE_MEMBER_NO, L.SEND_MEMBER_NO, L.ENROLL_DATE, L.STATUS, M.MEMBER_NICK
              FROM LETTER L
              JOIN MEMBER M ON (L.SEND_MEMBER_NO = M.MEMBER_NO)
              WHERE L.STATUS = 'O' AND L.RECEIVE_MEMBER_NO = ?
              ORDER BY L.SEND_MEMBER_NO DESC
            ) T
     )
WHERE RNUM BETWEEN ? AND ?;

--ƒ´øÓ∆Æ
SELECT COUNT(*)
FROM 
( SELECT L.LETTER_NO, L.LETTER_TITLE, L.LETTER_CONTENT, L.SEND_MEMBER_NO, L.ENROLL_DATE, L.STATUS, M.MEMBER_NICK
  FROM LETTER L
  JOIN MEMBER M ON (L.RECEIVE_MEMBER_NO = M.MEMBER_NO)
  WHERE L.STATUS = 'O' AND L.RECEIVE_MEMBER_NO = ?
) ;

--letterWrite
INSERT INTO LETTER (LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, STATUS)
VALUES (SEQ_LETTER_NO.NEXTVAL,(SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = 'Ω…ø¯øÎ'), (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = 'Ω…Ω øÎ'),'≈◊Ω∫§∑∆Æ', '§∑≈◊Ω∫∆Æ', 'O');

INSERT INTO LETTER (LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, STATUS)
VALUES (SEQ_LETTER_NO.NEXTVAL, (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = ?), (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK = ?), ?, ?, 'O');

-- sendLetter
SELECT * FROM ( SELECT ROWNUM RNUM, T.* 
FROM ( SELECT L.LETTER_NO, L.LETTER_TITLE, L.LETTER_CONTENT, L.SEND_MEMBER_NO, L.SEND_MEMBER_NO, L.ENROLL_DATE, L.STATUS, M.MEMBER_NICK
FROM LETTER L
JOIN MEMBER M ON (L.SEND_MEMBER_NO = M.MEMBER_NO)
WHERE L.STATUS = 'O' AND L.RECEIVE_MEMBER_NO = 1
ORDER BY L.RECEIVE_MEMBER_NO DESC ) T )
WHERE RNUM BETWEEN 1 AND 10;

SELECT * 
FROM (
    SELECT ROWNUM RNUM, T.*
    FROM (
        SELECT L.LETTER_NO, L.LETTER_TITLE, L.LETTER_CONTENT, L.SEND_MEMBER_NO, L.RECEIVE_MEMBER_NO, L.ENROLL_DATE, L.STATUS, M.MEMBER_NICK
        FROM LETTER L
        JOIN MEMBER M ON (L.SEND_MEMBER_NO = M.MEMBER_NO)
        WHERE L.STATUS = 'O' AND L.SEND_MEMBER_NO = 1
        ORDER BY L.RECEIVE_MEMBER_NO DESC
    ) T
)
WHERE RNUM BETWEEN 1 AND 10;

SELECT * 
FROM ( SELECT ROWNUM RNUM, T.*
FROM ( SELECT * FROM MEMBER M JOIN LETTER L ON (M.MEMBER_NO = L.SEND_MEMBER_NO)
WHERE L.STATUS = 'O' AND M.MEMBER_NICK LIKE '%'||'≈ı'||'%' ORDER BY M.MEMBER_NO DESC ) T ) 
WHERE SEND_MEMBER_NO = 1
AND RNUM BETWEEN 1 AND 10;

SELECT * 
FROM ( SELECT ROWNUM RNUM, T.*
FROM ( SELECT * FROM MEMBER M JOIN LETTER L ON M.MEMBER_NO = L.SEND_MEMBER_NO
WHERE L.STATUS = 'O' AND L.RECEIVE_MEMBER_NO IN (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NICK  LIKE '%?%' ) ORDER BY M.MEMBER_NO DESC ) T )
WHERE SEND_MEMBER_NO = ? 
AND RNUM BETWEEN ? AND ?;

SELECT * FROM LETTER;
SELECT * FROM MEMBER;

SELECT (SELECT SEND_MEMBER_NAME FROM LETTER L JOIN MEMBER M ON L.SEND_MEMBER_NO = M.MEMBER_NO),  LETTER_TITLE, LETTER_CONTENT, ENROLL_DATE
FROM LETTER L
JOIN MEMBER M ON M.MEMBER_NO = L.SEND_MEMBER_NO
;


SELECT * FROM LETTER L
JOIN MEMBER M ON L.SEND_MEMBER_NO = M.MEMBER_NO
WHERE SEND_MEMBER_NO = 1;



select * FROM LETTER L
where letter_no = 1;

SELECT MEMBER_NICK FROM MEMBER 
WHERE MEMBER_NO = 
(select SEND_MEMBER_NO FROM LETTER
where letter_no = 7);


--AND SEND_MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER FETCH FIRST 1 ROW ONLY WHERE MEMBER_NICK = '' )
--AND RECEIVE_MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER FETCH FIRST 1 ROW ONLY WHERE MEMBER_NICK = '' )
;

SELECT LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, ENROLL_DATE 
FROM LETTER 
WHERE LETTER_NO = 4;






