--Î∞õÏ? Î©îÏÑ∏Ïß??óê?Ñú OPT Í≤??Éâ?ïòÍ∏?
SELECT * 
FROM 
(
    SELECT ROWNUM RNUM, T.* FROM
        (
            SELECT * 
            FROM MEMBER M
            JOIN LETTER L ON (M.MEMBER_NO = L.SEND_MEMBER_NO)
            WHERE L.STATUS = 'O' AND M.MEMBER_ID LIKE '%'||?||'%' ORDER BY M.MEMBER_NO DESC
        ) T
)
WHERE RNUM BETWEEN ? AND ?;

--Í∑∏ÎÉ• Í≤??Éâ
SELECT * 
FROM 
    ( 
        SELECT ROWNUM RNUM , T.* 
        FROM
        ( 
            SELECT L.LETTER_NO , L.LETTER_TITLE , L.LETTER_CONTENT , L.SEND_MEMBER_NO , L.ENROLL_DATE , L.STATUS , M.MEMBER_NICK
            FROM LETTER L
            JOIN MEMBER M ON(L.SEND_MEMBER_NO = M.MEMBER_NO)
            WHERE L.STATUS = 'O' ORDER BY MEMBER_NO DESC
        )T 
    )
    WHERE RNUM BETWEEN ? AND ?;


--Î©îÏÑ∏Ïß? Ï¥? Í∞úÏàò
SELECT COUNT(*)
FROM ( 
        SELECT L.LETTER_NO , L.LETTER_TITLE , L.LETTER_CONTENT , L.SEND_MEMBER_NO , L.ENROLL_DATE , L.STATUS , M.MEMBER_NICK
        FROM LETTER L
        JOIN MEMBER M ON(L.SEND_MEMBER_NO = M.MEMBER_NO)
    )
WHERE STATUS = 'O';

select * from letter;


INSERT INTO 
LETTER (LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT, STATUS)
VALUES (SEQ_LETTER_NO.NEXTVAL,'1', (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_NO = 2),'æ¥®', '§∑§∑', 'O');

























