-- ���̵�����

-- LECTURE_CATEGORY
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '������ UI/UX �������� ������ �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���������� ���� �� ���ø����̼� ������ �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���������� ���� �ڹٰ����� �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���ȿ����Ͼ ��� �������� ������ �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '������ �������� ���������� �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '����Ʈ��, ���������� UI/UX ������ �缺���� A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '������ UI/UX �������� ������ �缺���� B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���������� ���� �� ���ø����̼� ������ �缺���� B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���������� ���� �ڹٰ����� �缺���� B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '���ȿ����Ͼ ��� �������� ������ �缺���� B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '������ �������� ���������� �缺���� B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '����Ʈ��, ���������� UI/UX ������ �缺���� B');

-- EXAM_CATEGORY
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '���α׷��� ��� ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI ��Ű���� ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '���� �����ͺ��̽� ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL Ȱ��');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI ������');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '�䱸���� Ȯ��');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '�������α׷� ����');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX �䱸 �м�');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX �ܼ�Ʈ ��ȹ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '���ø����̼� ����');

-- MEMBER
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', '�ɿ���', '0000000000001', '01000000001','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', '1234', '������', '0000000000002', '01000000002','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', '1234', '�ɻ��', '0000000000003', '01000000003','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', '1234', '�ɻ��', '0000000000004', '01000000004','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', '1234', '�ɿ���', '0000000000005', '01000000005','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', '1234', '������', '0000000000006', '01000000006','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user07', '1234', '��ĥ��', '0000000000007', '01000000007','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user08', '1234', '���ȿ�', '0000000000008', '01000000008','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user09', '1234', '�ɱ���', '0000000000009', '01000000009','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user10', '1234', '�ɿ���', '0000000000010', '01000000010','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user11', '1234', '�ɿ��ϳ���', '0000000000011', '01000000011','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user12', '1234', '�ɿ��ѿ�', '0000000000012', '01000000012','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user001', '1234', '���Ͽ�', '1000000000001', '01010000001','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user002', '1234', '���̿�', '1000000000002', '01010000002','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user003', '1234', '�ɻ��', '1000000000003', '01010000003','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user004', '1234', '�ɻ��', '1000000000004', '01010000004','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user005', '1234', '�ɿ���', '1000000000005', '01010000005','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user006', '1234', '������', '1000000000006', '01010000006','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user007', '1234', '��ĥ��', '1000000000007', '01010000007','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user008', '1234', '���ȿ�', '1000000000008', '01010000008','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user009', '1234', '�ɱ���', '1000000000009', '01010000009','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user010', '1234', '�ɽʿ�', '1000000000010', '01010000010','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user011', '1234', '�ɽ��Ͽ�', '1000000000011', '01100000011','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user012', '1234', '�ɽ��̿�', '1000000000012', '01100000012','T');

-- LECTURE
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 14, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 15, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 16, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 17, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 18, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 19, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 20, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 21, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 22, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 23, 1, 1530, 2200, 20221230, 20230816, 'O');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 24, 1, 1530, 2200, 20221230, 20230816, 'O');

-- LETTER
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 2, '����1', '����1');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 3, '����2', '����2');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 4, '����3', '����3');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 5, '����4', '����4');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 6, '����5', '����5');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 7, '����6', '����6');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 2, 1, '����7', '����7');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 3, 1, '����8', '����8');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 4, 1, '����9', '����9');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 5, 1, '����10', '����10');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 6, 1, '����11', '����11');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 7, 1, '����12', '����12');

-- PROBLEM_BANK
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '���α׷���?', '���α׷�', 10);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '1+1?', '3', 20);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '��������', '���̽�ũ��', 30);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '�츮����', '����� ��', 40);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '�����', '�ɿ��� �����', 50);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '���� ����ö', '����ö', 10);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'GET', 'SET', 20);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'READY', 'GO', 30);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '��', '�ΰ� ��', 40);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ERD', 'CLOUD', 50);
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '��������', '��������', 100);

-- ADMIN
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN01', '1234', '������01', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN02', '1234', '������02', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN03', '1234', '������03', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN04', '1234', '������04', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN05', '1234', '������05', 'O', 1);

-- BOARD_CATEGORY
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '���͵� ����');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '�Ļ� ������');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '������');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '������');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '��������');

-- BOARD
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', 'ù��° ��', 'ù�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '�ι�° ��', '2�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '����° ��', '3�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '�׹�° ��', '4�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '�ټ���° ��', '5�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '������° ��', '6�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '�ϰ���° ��', '7�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '����° ��', '8�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '��ȩ° ��', '9�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '����° ��', '10�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '���ѹ�° ��', '11�� °�� �� ���� ��', SYSDATE, SYSDATE, 'O', '0');

-- BOARD_PHOTO
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO01');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO02');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO03');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO04');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO05');

--REPLY
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���1', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���2', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���3', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���4', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���5', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���6', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���7', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���8', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���9', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '����̿���0', SYSDATE, SYSDATE, 'O');

-- ANSWER
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ01', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ02', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ03', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ04', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ05', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ06', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ07', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ08', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ09', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ10', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '���ù�����ȸ11', SYSDATE, SYSDATE, 'O');

--NOTICE
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '���̶�1', '�����������1', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�2', '�����������2', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�3', '�����������3', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�4', '�����������4', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�5', '�����������5', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�6', '�����������6', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�7', '�����������7', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�8', '�����������8', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�9', '�����������9', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�10', '�����������10', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '���̶�11', '�����������11', SYSDATE, SYSDATE, '1', 'O');

--NOTICE_PHOTO
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '1', 'AAA');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '2', 'BBB');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '3', 'CCC');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '4', 'DDD');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '5', 'EEE');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '6', 'FFF');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '7', 'GGG');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '8', 'HHH');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '9', 'III');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '10', 'KKK');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '11', 'LLL');

--REVIEW
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����1', '���� ����1', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����2', '���� ����2', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����3', '���� ����3', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����4', '���� ����4', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����5', '���� ����5', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����6', '���� ����6', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����7', '���� ����7', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����8', '���� ����8', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����9', '���� ����9', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����10', '���� ����10', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '���� ����11', '���� ����11', SYSDATE, SYSDATE, 'AAA', 'O');

--TEAM
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '1��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '2��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '3��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '4��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '5��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '6��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '7��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '8��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '9��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '10��');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '11��');

--STUDENT
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(1, 1, 1, 0);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(2, 1, 1, 10);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(3, 1, 1, 20);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(4, 1, 1, 30);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(5, 1, 1, 40);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(6, 2, 1, 50);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(7, 2, 1, 60);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(8, 2, 1, 70);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(9, 2, 1, 80);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(10, 2, 1, 90);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(11, 3, 2, 100);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(12, 3, 2, 110);

-- ATTENDANCE_LIST
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '1', SYSDATE, SYSDATE, 'X');

-- EXAM_LIST
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 1, 10);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 2, 20);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 3, 30);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 4, 40);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 5, 50);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 6, 60);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 7, 70);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 8, 80);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 9, 90);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 10, 100);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 11, 10);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 12, 20);

--QNA
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '�̰� �ȵǴµ�', '�̰� �۵��� �ȵǴµ�', '���� �غ�����', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '��', '�����', '���� ������', SYSDATE, SYSDATE, 'BBB', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ1', '����1', '���1', SYSDATE, SYSDATE, 'AAA1', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ2', '����2', '���2', SYSDATE, SYSDATE, 'AAA2', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ3', '����3', '���3', SYSDATE, SYSDATE, 'AAA3', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ4', '����4', '���4', SYSDATE, SYSDATE, 'AAA4', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ5', '����5', '���5', SYSDATE, SYSDATE, 'AAA5', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ6', '����6', '���6', SYSDATE, SYSDATE, 'AAA6', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ7', '����7', '���7', SYSDATE, SYSDATE, 'AAA7', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ8', '����8', '���8', SYSDATE, SYSDATE, 'AAA8', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Ÿ��Ʋ9', '����9', '���9', SYSDATE, SYSDATE, 'AAA9', 'O');

--SUBMIT_ANSWER
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 1, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 2, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 3, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 4, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 5, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 1, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 2, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 3, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 4, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 5, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 1, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 2, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 3, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 4, '����Դϴ�');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 5, '����Դϴ�');

--VACATION_REQUEST_LIST
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230202', '20230202', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230303', '20230303', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230404', '20230404', 'X');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230202', '20230202', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230303', '20230303', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230404', '20230404', 'X');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230202', '20230202', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230303', '20230303', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230404', '20230404', 'X');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230202', '20230202', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230303', '20230303', 'O');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230404', '20230404', 'O');

--TEAM_ROLE
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 1, '����', '�̴�');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 2, 'DB������', '�̴�');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 3, '���������', '�̴�');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 4, '����Ʈ������', '�̴�');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 5, '�̽�������', '�̴�');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 6, '����', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 7, 'DB������', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 8, '���������', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 9, '����Ʈ������', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 10, '�̽�������', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 11, '����', '����');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 12, 'DB������', '����');

--TEAM_CALANDER
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', 'ȸ��');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', 'ȸ��');


COMMIT;
---------------------------
--SELECT * FROM ADMIN;
--SELECT * FROM ANSWER;
--SELECT * FROM ATTENDANCE_LIST;
--SELECT * FROM BOARD;
--SELECT * FROM BOARD_CATEGORY;
--SELECT * FROM BOARD_PHOTO;
--SELECT * FROM EXAM_CATEGORY;
--SELECT * FROM EXAM_LIST;
--SELECT * FROM LECTURE;
--SELECT * FROM LECTURE_CATEGORY;
--SELECT * FROM LETTER;
--SELECT * FROM MEMBER;
--SELECT * FROM NOTICE;
--SELECT * FROM NOTICE_PHOTO;
--SELECT * FROM PROBLEM_BANK;
--SELECT * FROM QNA;
--SELECT * FROM REPLY;
--SELECT * FROM REVIEW;
--SELECT * FROM STUDENT;
--SELECT * FROM SUBMIT_ANSWER;
--SELECT * FROM TEAM;
--SELECT * FROM TEAM_CALENDER;
--SELECT * FROM TEAM_ROLE;
--SELECT * FROM VACATION_REQUEST_LIST;
