-- 더미데이터

-- LECTURE_CATEGORY
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '반응형 UI/UX 웹콘텐츠 개발자 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '공공데이터 융합 웹 애플리케이션 개발자 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '공공데이터 융합 자바개발자 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '보안엔지니어링 기반 정보보안 전문가 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '디지털 컨버전스 공공개발자 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '스마트웹, 콘텐츠개발 UI/UX 개발자 양성과정 A');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '반응형 UI/UX 웹콘텐츠 개발자 양성과정 B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '공공데이터 융합 웹 애플리케이션 개발자 양성과정 B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '공공데이터 융합 자바개발자 양성과정 B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '보안엔지니어링 기반 정보보안 전문가 양성과정 B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '디지털 컨버전스 공공개발자 양성과정 B');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '스마트웹, 콘텐츠개발 UI/UX 개발자 양성과정 B');

-- EXAM_CATEGORY
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '프로그래밍 언어 응용');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI 아키텍쳐 설계');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '물리 데이터베이스 설계');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL 활용');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL 응용');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI 디자인');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI 구현');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '요구사항 확인');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '서버프로그램 구현');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX 요구 분석');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX 콘셉트 기획');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '애플리케이션 설계');

-- MEMBER
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', '심원용', '0000000000001', '01000000001','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', '1234', '심투용', '0000000000002', '01000000002','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', '1234', '심삼용', '0000000000003', '01000000003','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', '1234', '심사용', '0000000000004', '01000000004','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', '1234', '심오용', '0000000000005', '01000000005','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', '1234', '심육용', '0000000000006', '01000000006','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user07', '1234', '심칠용', '0000000000007', '01000000007','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user08', '1234', '심팔용', '0000000000008', '01000000008','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user09', '1234', '심구용', '0000000000009', '01000000009','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user10', '1234', '심열용', '0000000000010', '01000000010','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user11', '1234', '심열하나용', '0000000000011', '01000000011','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user12', '1234', '심열둘용', '0000000000012', '01000000012','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user001', '1234', '심일용', '1000000000001', '01010000001','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user002', '1234', '심이용', '1000000000002', '01010000002','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user003', '1234', '심삼용', '1000000000003', '01010000003','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user004', '1234', '심사용', '1000000000004', '01010000004','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user005', '1234', '심오용', '1000000000005', '01010000005','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user006', '1234', '심육용', '1000000000006', '01010000006','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user007', '1234', '심칠용', '1000000000007', '01010000007','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user008', '1234', '심팔용', '1000000000008', '01010000008','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user009', '1234', '심구용', '1000000000009', '01010000009','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user010', '1234', '심십용', '1000000000010', '01010000010','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user011', '1234', '심십일용', '1000000000011', '01100000011','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user012', '1234', '심십이용', '1000000000012', '01100000012','T');

-- LECTURE
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 1, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 2, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 3, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 4, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 5, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 14, 1, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 15, 1, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 16, 1, 1530, 2200, 20221230, 20230816, 'O', '강남');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 17, 1, 1530, 2200, 20221230, 20230816, 'O', '당산');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 18, 1, 1530, 2200, 20221230, 20230816, 'O', '당산');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 19, 1, 1530, 2200, 20221230, 20230816, 'O', '당산');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 20, 1, 1530, 2200, 20221230, 20230816, 'O', '당산');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 21, 1, 1530, 2200, 20221230, 20230816, 'O', '종로');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 22, 1, 1530, 2200, 20221230, 20230816, 'O', '종로');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 23, 1, 1530, 2200, 20221230, 20230816, 'O', '종로');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 24, 1, 1530, 2200, 20221230, 20230816, 'O', '종로');

-- LETTER
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 2, '제목1', '내용1');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 3, '제목2', '내용2');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 4, '제목3', '내용3');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 5, '제목4', '내용4');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 6, '제목5', '내용5');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 7, '제목6', '내용6');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 2, 1, '제목7', '내용7');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 3, 1, '제목8', '내용8');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 4, 1, '제목9', '내용9');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 5, 1, '제목10', '내용10');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 6, 1, '제목11', '내용11');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 7, 1, '제목12', '내용12');

-- PROBLEM_BANK
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '프로그램은?', '프로그램', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '1+1?', '3', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '집에갈땐', '아이스크림', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '우리집은', '누우면 집', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '강사는', '심원용 강사님', 50, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '버스 지하철', '지하철', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'GET', 'SET', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'READY', 'GO', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '김', '민과 성', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ERD', 'CLOUD', 50, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '내리막길', '오르막길', 100, 'O');

-- ADMIN
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN01', '1234', '관리자01', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN02', '1234', '관리자02', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN03', '1234', '관리자03', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN04', '1234', '관리자04', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN05', '1234', '관리자05', 'O', 1);

-- BOARD_CATEGORY
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (01, '자유게시판');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (02, '문의게시판');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (03, '우리반게시판');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (04, '공지사항');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (05, '수강후기');

-- BOARD
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '첫번째 글', '첫번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '두번째 글', '2번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '세번째 글', '3번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '2', '네번째 글', '4번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '2', '다섯번째 글', '5번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '3', '여섯번째 글', '6번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '4', '일곱번째 글', '7번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '5', '여덟째 글', '8번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '5', '아홉째 글', '9번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '6', '열번째 글', '10번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '6', '열한번째 글', '11번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');

INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '1', '첫번째 글', '첫번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '1', '두번째 글', '2번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '2', '세번째 글', '3번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '3', '네번째 글', '4번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '4', '다섯번째 글', '5번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '5', '여섯번째 글', '6번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '6', '일곱번째 글', '7번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '6', '여덟째 글', '8번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '1', '아홉째 글', '9번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '2', '열번째 글', '10번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '2', '5', '열한번째 글', '11번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');

INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', '첫번째 글', '첫번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', '두번째 글', '2번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '6', '세번째 글', '3번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '네번째 글', '4번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', '다섯번째 글', '5번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', '여섯번째 글', '6번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', '일곱번째 글', '7번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '6', '여덟째 글', '8번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '아홉째 글', '9번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '열번째 글', '10번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', '열한번째 글', '11번 째로 글 쓰고 감', SYSDATE, SYSDATE, 'O', '0');

-- BOARD_PHOTO
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO01');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO02');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO03');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO04');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO05');

--REPLY
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '대답이에요', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '1', '대답이에요1', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '5', '7', '대답이에요2', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '7', '대답이에요3', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '5', '8', '대답이에요4', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '2', '9', '대답이에요5', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '4', '2', '대답이에요6', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '3', '대답이에요7', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '6', '5', '대답이에요8', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '7', '2', '대답이에요9', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '8', '3', '대답이에요0', SYSDATE, SYSDATE, 'O');

-- ANSWER
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '무플방지협회01', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '무플방지협회02', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 3, '무플방지협회03', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 3, '무플방지협회04', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 5, '무플방지협회05', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 6, '무플방지협회06', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 7, '무플방지협회07', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 2, '무플방지협회08', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 2, '무플방지협회09', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '무플방지협회10', SYSDATE, SYSDATE, 'O');
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '무플방지협회11', SYSDATE, SYSDATE, 'O');

--NOTICE
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '집이란1', '집에보내줘요1', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란2', '집에보내줘요2', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란3', '집에보내줘요3', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란4', '집에보내줘요4', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란5', '집에보내줘요5', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란6', '집에보내줘요6', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란7', '집에보내줘요7', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란8', '집에보내줘요8', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란9', '집에보내줘요9', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란10', '집에보내줘요10', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '집이란11', '집에보내줘요11', SYSDATE, SYSDATE, '1', 'O');

--NOTICE_PHOTO
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '1', 'AAA');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '2', 'BBB');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '3', 'CCC');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '4', 'DDD');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '5', 'EEE');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '6', 'FFF');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '7', 'GGG');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '8', 'HHH');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '9', 'III');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '10', 'KKK');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '11', 'LLL');

--REVIEW
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목1', '리뷰 내용1', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목2', '리뷰 내용2', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목3', '리뷰 내용3', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목4', '리뷰 내용4', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목5', '리뷰 내용5', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목6', '리뷰 내용6', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목7', '리뷰 내용7', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목8', '리뷰 내용8', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목9', '리뷰 내용9', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목10', '리뷰 내용10', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '리뷰 제목11', '리뷰 내용11', SYSDATE, SYSDATE, 'AAA', 'O');

--TEAM
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '1조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '2조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '3조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '4조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '5조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '6조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '7조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '8조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '9조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '10조');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '11조');

--STUDENT
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(1, 1, 1, 0);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(2, 1, 1, 10);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(3, 1, 1, 20);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(4, 1, 1, 30);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(5, 1, 1, 40);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(6, 1, 1, 50);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(7, 1, 1, 60);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(8, 1, 1, 70);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(9, 1, 1, 80);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(10, 2, 1, 90);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(11, 3, 2, 100);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(12, 3, 2, 110);

-- ATTENDANCE_LIST
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '1', SYSDATE, SYSDATE, 'X');

-- EXAM_LIST
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 1, 10);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 2, 20);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 3, 30);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 4, 40);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 5, 50);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 6, 60);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 7, 70);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 8, 80);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 9, 90);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 10, 100);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 11, 10);
INSERT INTO EXAM_LIST(EXAM_SCORE_NO, EXAM_CATEGORY_NO, MEMBER_NO, SCORE) VALUES(SEQ_EXAM_LIST_NO.NEXTVAL, 1, 12, 20);

--QNA
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '이거 안되는데', '이거 작동이 안되는데', '저거 해보세요', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '나', '힘들어', '저도 힘들어요', SYSDATE, SYSDATE, 'BBB', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '타이틀1', '내용1', '대답1', SYSDATE, SYSDATE, 'AAA1', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', '타이틀2', '내용2', '대답2', SYSDATE, SYSDATE, 'AAA2', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', '타이틀3', '내용3', '대답3', SYSDATE, SYSDATE, 'AAA3', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', '타이틀4', '내용4', '대답4', SYSDATE, SYSDATE, 'AAA4', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', '타이틀5', '내용5', '대답5', SYSDATE, SYSDATE, 'AAA5', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', '타이틀6', '내용6', '대답6', SYSDATE, SYSDATE, 'AAA6', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', '타이틀7', '내용7', '대답7', SYSDATE, SYSDATE, 'AAA7', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '4', '타이틀8', '내용8', '대답8', SYSDATE, SYSDATE, 'AAA8', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '4', '타이틀9', '내용9', '대답9', SYSDATE, SYSDATE, 'AAA9', 'O');

--SUBMIT_ANSWER
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 1, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 2, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 3, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 4, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 1, 5, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 1, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 2, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 3, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 4, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 2, 5, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 1, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 2, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 3, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 4, '답안입니다');
INSERT INTO SUBMIT_ANSWER(SUBMIT_ANSWER_NO, EXAM_SCORE_NO, EXAM_PROBLEM_NO, SUBMIT_ANSWER) VALUES(SEQ_SUBMIT_ANSWER_NO.NEXTVAL, 3, 5, '답안입니다');

--VACATION_REQUEST_LIST
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230202', '20230202', 'O', '결혼식');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230303', '20230303', 'O', '여행');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230404', '20230404', 'X', '조부상');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230202', '20230202', 'O', '휴식');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230303', '20230303', 'O', '입원');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230404', '20230404', 'X', '나들이');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230202', '20230202', 'O', '발목 부상');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230303', '20230303', 'O', '싱싱미역');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230404', '20230404', 'X', '히히');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230202', '20230202', 'O', '병원');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230303', '20230303', 'O', '면접');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230404', '20230404', 'O', '헤헤');

--TEAM_ROLE
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 1, '조장', '미니');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 2, 'DB관리자', '미니');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 3, '형상관리자', '미니');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 4, '프론트관리자', '미니');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 5, '이슈관리자', '미니');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 6, '조장', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 7, 'DB관리자', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 8, '형상관리자', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 9, '프론트관리자', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 10, '이슈관리자', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 11, '조장', '세미');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 12, 'DB관리자', '세미');

--TEAM_CALANDER
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 1, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 2, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 3, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', '회의');
INSERT INTO TEAM_CALENDER(TEAM_CALENDER_NO, TEAM_NO, MEETING_DATE, MEETING_CONTENT) VALUES(SEQ_TEAM_CALENDER_NO.NEXTVAL, 4, '2023-01-01 12:30:00', '회의');

COMMIT;
---------------------------
--SELECT * FROM ADMIN;
--SELECT * FROM ANSWER;
--SELECT * FROM ATTENDANCE_LIST;
--SELECT * FROM BOARD;
--SELECT * FROM BOARD_CATEGORY;
--SELECT * FROM BOARD_PHOTO;
--SELECT * FROM EXAM_CATEGORY;
--SELECT * FROM EXAM_LIST;
--SELECT * FROM LECTURE;
--SELECT * FROM LECTURE_CATEGORY;
--SELECT * FROM LETTER;
--SELECT * FROM MEMBER;
--SELECT * FROM NOTICE;
--SELECT * FROM NOTICE_PHOTO;
--SELECT * FROM PROBLEM_BANK;
--SELECT * FROM QNA;
--SELECT * FROM REPLY;
--SELECT * FROM REVIEW;
--SELECT * FROM STUDENT;
--SELECT * FROM SUBMIT_ANSWER;
--SELECT * FROM TEAM;
--SELECT * FROM TEAM_CALENDER;
--SELECT * FROM TEAM_ROLE;
--SELECT * FROM VACATION_REQUEST_LIST;