-- ´õ¹Ìµ¥ÀÌÅÍ

-- LECTURE_CATEGORY
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, '°³¹ßÀÚ ¾ç¼º°úÁ¤');
INSERT INTO LECTURE_CATEGORY VALUES(SEQ_LECTURE_CATEGORY_NO.NEXTVAL, 'Á¤º¸º¸¾È Àü¹®°¡');

-- EXAM_CATEGORY
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'ÇÁ·Î±×·¡¹Ö ¾ð¾î ÀÀ¿ë');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'ÇÁ·Î±×·¡¹Ö ¾ð¾î ÀÀ¿ë');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI ¾ÆÅ°ÅØÃÄ ¼³°è');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '¹°¸® µ¥ÀÌÅÍº£ÀÌ½º ¼³°è');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL È°¿ë');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'SQL ÀÀ¿ë');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI µðÀÚÀÎ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI ±¸Çö');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '¿ä±¸»çÇ× È®ÀÎ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '¼­¹öÇÁ·Î±×·¥ ±¸Çö');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX ¿ä±¸ ºÐ¼®');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, 'UI/UX ÄÜ¼ÁÆ® ±âÈ¹');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 1, '¾ÖÇÃ¸®ÄÉÀÌ¼Ç ¼³°è');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'NW º¸¾È ±¸Ãà');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'Á¤º¸ ½Ã½ºÅÛ Áø´Ü');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '°ü¸®Àû º¸¾È ±¸Ãà');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '°ü¸®Àû º¸¾È ¿î¿µ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '½Ã½ºÅÛ º¸¾È ±¸Ãà');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'Á¤º¸º¸È£ °èÈ¹ ¼ö¸³');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'º¸¾È À§Çè°ü¸®');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '³×Æ®¿öÅ© º¸¾È ¿î¿µ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'º¸¾È Àåºñ ¿î¿ë');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'º¸¾È ·Î±× ºÐ¼®');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '¹°¸® º¸¾È ¿î¿µ');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, '¸ðÀÇ ÇØÅ·');
INSERT INTO EXAM_CATEGORY VALUES(SEQ_EXAM_CATEGORY_NO.NEXTVAL, 2, 'º¸¾È ±¸Ãà °èÈ¹ ¼ö¸³');

-- MEMBER
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', '1234', '½É¿ø¿ë', '00000001', '01000000001','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', '1234', '½ÉÅõ¿ë', '00000002', '01000000002','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', '1234', '½É»ï¿ë', '00000003', '01000000003','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', '1234', '½É»ç¿ë', '00000004', '01000000004','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', '1234', '½É¿À¿ë', '00000005', '01000000005','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', '1234', '½ÉÀ°¿ë', '00000006', '01000000006','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user07', '1234', '½ÉÄ¥¿ë', '00000007', '01000000007','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user08', '1234', '½ÉÆÈ¿ë', '00000008', '01000000008','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user09', '1234', '½É±¸¿ë', '00000009', '01000000009','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user10', '1234', '½É¿­¿ë', '00000010', '01000000010','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user11', '1234', '½É¿­ÇÏ³ª¿ë', '00000011', '01000000011','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user12', '1234', '½É¿­µÑ¿ë', '00000012', '01000000012','S');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user001', '1234', '½ÉÀÏ¿ë', '10000001', '01010000001','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user002', '1234', '½ÉÀÌ¿ë', '10000002', '01010000002','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user003', '1234', '½É»ï¿ë', '10000003', '01010000003','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user004', '1234', '½É»ç¿ë', '10000004', '01010000004','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user005', '1234', '½É¿À¿ë', '10000005', '01010000005','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user006', '1234', '½ÉÀ°¿ë', '10000006', '01010000006','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user007', '1234', '½ÉÄ¥¿ë', '10000007', '01010000007','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user008', '1234', '½ÉÆÈ¿ë', '10000008', '01010000008','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user009', '1234', '½É±¸¿ë', '10000009', '01010000009','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user010', '1234', '½É½Ê¿ë', '10000010', '01010000010','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user011', '1234', '½É½ÊÀÏ¿ë', '10000011', '01100000011','T');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, BIRTH_NUM, PHONE_NO, IDENTITY) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user012', '1234', '½É½ÊÀÌ¿ë', '10000012', '01100000012','T');

-- LECTURE
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 1, '0900', 1530, 20221230, 20230816, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 13, 2, 1530, 2200, 20230102, 20230819, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 14, 2, '0900', 1530, 20230430, 20231113, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 14, 2, 1530, 2200, 20230430, 20231113, 'O', 'Á¾·Î');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 15, 1, 1530, 2200, 20230630, 20231216, 'O', '´ç»ê');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 15, 1, '0900', 1530, 20230630, 20231216, 'O', '´ç»ê');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 16, 2, '0900', 1800, 20230620, 20231106, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 17, 1, '0900', 1800, 20230610, 20231026, 'O', '´ç»ê');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 18, 2, 1530, 2200, 20230701, 20240113, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 19, 1, '0900', 1530, 20230705, 20240125, 'O', '°­³²');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 20, 1, '0900', 1530, 20230708, 20240128, 'O', 'Á¾·Î');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 21, 2, 1530, 2200, 20230712, 20240213, 'O', '´ç»ê');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 22, 2, 1530, 2200, 20230720, 20240215, 'O', '´ç»ê');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 23, 1, '0900', 1530, 20230728, 20240219, 'O', 'Á¾·Î');
INSERT INTO LECTURE VALUES(SEQ_LECTURE_NO.NEXTVAL, 24, 1, '0900', 1800, 20230729, 20240113, 'O', '´ç»ê');

-- LETTER
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 2, 'Á¦¸ñ1', '³»¿ë1');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 3, 'Á¦¸ñ2', '³»¿ë2');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 4, 'Á¦¸ñ3', '³»¿ë3');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 5, 'Á¦¸ñ4', '³»¿ë4');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 6, 'Á¦¸ñ5', '³»¿ë5');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 1, 7, 'Á¦¸ñ6', '³»¿ë6');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 2, 1, 'Á¦¸ñ7', '³»¿ë7');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 3, 1, 'Á¦¸ñ8', '³»¿ë8');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 4, 1, 'Á¦¸ñ9', '³»¿ë9');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 5, 1, 'Á¦¸ñ10', '³»¿ë10');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 6, 1, 'Á¦¸ñ11', '³»¿ë11');
INSERT INTO LETTER(LETTER_NO, SEND_MEMBER_NO, RECEIVE_MEMBER_NO, LETTER_TITLE, LETTER_CONTENT) VALUES(SEQ_LETTER_NO.NEXTVAL, 7, 1, 'Á¦¸ñ12', '³»¿ë12');


-- PROBLEM_BANK
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ÇÁ·Î±×·¥Àº?', 'ÇÁ·Î±×·¥', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '1+1?', '2', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'Áý¿¡°¥¶©', '¾ÆÀÌ½ºÅ©¸²', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '¿ì¸®ÁýÀº', '´©¿ì¸é Áý', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '°­»ç´Â', '½É¿ø¿ë °­»ç´Ô', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '¹ö½º ÁöÇÏÃ¶', 'ÁöÇÏÃ¶', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'GET', 'SET', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'READY', 'GO', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ºñºñ°í', '¸¸µÎ', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ajax´Â?', 'À¯¿ëÇÏ´Ù', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'spring ¹è¿ì¸é ÁÁ°Ú´Ù', 'È÷È÷', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '¾È³çÇÏ½Å°¡', '¾È¾ÆÁà¿ä', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '¹è°íÇÃ¶©?', '¾ß½ÄÀÌÁö', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '±×´ë ±â¾ïÀÌ', 'Áö³­ »ç¶ûÀÌ', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', '³»ÀÌ¸§Àº Á¤»ó¼ö', '¹é¹ß¹éÁßÇÏ´Â ¸í»ç¼ö', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '1', 'ºÎ»êÁø±¸ À¯¸í°¡¼ö', 'ÀÏÃë¿ùÀåÇÏ¸ç ¼ºÀåÁß', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', '¾È³ç', 'ÇÏ¼¼¿ä', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', 'ERD', 'CLOUD', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', '³»¸®¸·±æ', '¿À¸£¸·±æ', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', 'ÆR', 'Å±Å±', 40, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', 'ÇÁ·Î±×·¥Àº?', 'ÇÁ·Î±×·¥', 10, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', '1+1?', '3', 20, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', 'Áý¿¡°¥¶©', '¾ÆÀÌ½ºÅ©¸²', 30, 'O');
INSERT INTO "C##KH_UNIV"."PROBLEM_BANK" VALUES (SEQ_PROBLEM_BANK_NO.NEXTVAL, '2', '¿ì¸®ÁýÀº', '´©¿ì¸é Áý', 40, 'O');

-- ADMIN
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN01', '1234', '°ü¸®ÀÚ01', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN02', '1234', '°ü¸®ÀÚ02', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN03', '1234', '°ü¸®ÀÚ03', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN04', '1234', '°ü¸®ÀÚ04', 'O', 1);
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NICK, STATUS, QUALIFICATION) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN05', '1234', '°ü¸®ÀÚ05', 'O', 1);

-- BOARD_CATEGORY
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (01, 'ÀÚÀ¯°Ô½ÃÆÇ');
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_TYPE) VALUES (03, '¿ì¸®¹Ý°Ô½ÃÆÇ');

-- BOARD
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', 'Ã¹¹øÂ° ±Û', 'Ã¹¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', 'µÎ¹øÂ° ±Û', '2¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '1', '¼¼¹øÂ° ±Û', '3¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '2', '³×¹øÂ° ±Û', '4¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '2', '´Ù¼¸¹øÂ° ±Û', '5¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '3', '¿©¼¸¹øÂ° ±Û', '6¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '4', 'ÀÏ°ö¹øÂ° ±Û', '7¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '5', '¿©´üÂ° ±Û', '8¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '5', '¾ÆÈ©Â° ±Û', '9¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '6', '¿­¹øÂ° ±Û', '10¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '1', '6', '¿­ÇÑ¹øÂ° ±Û', '11¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');

INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', 'Ã¹¹øÂ° ±Û', 'Ã¹¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', 'µÎ¹øÂ° ±Û', '2¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '6', '¼¼¹øÂ° ±Û', '3¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '³×¹øÂ° ±Û', '4¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', '´Ù¼¸¹øÂ° ±Û', '5¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', '¿©¼¸¹øÂ° ±Û', '6¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '3', 'ÀÏ°ö¹øÂ° ±Û', '7¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '6', '¿©´üÂ° ±Û', '8¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '¾ÆÈ©Â° ±Û', '9¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '4', '¿­¹øÂ° ±Û', '10¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '2', '¿­ÇÑ¹øÂ° ±Û', '11¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');


INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '7', 'Ã¹¹øÂ° ±Û', 'Ã¹¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '7', 'µÎ¹øÂ° ±Û', '2¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '8', '¼¼¹øÂ° ±Û', '3¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '8', '³×¹øÂ° ±Û', '4¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '8', '´Ù¼¸¹øÂ° ±Û', '5¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '9', '¿©¼¸¹øÂ° ±Û', '6¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '9', 'ÀÏ°ö¹øÂ° ±Û', '7¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '9', '¿©´üÂ° ±Û', '8¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '7', '¾ÆÈ©Â° ±Û', '9¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '8', '¿­¹øÂ° ±Û', '10¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');
INSERT INTO BOARD(BOARD_NO, BOARD_CATEGORY_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, HIT) VALUES (SEQ_BOARD_NO.NEXTVAL, '3', '9', '¿­ÇÑ¹øÂ° ±Û', '11¹ø Â°·Î ±Û ¾²°í °¨', SYSDATE, SYSDATE, 'O', '0');


-- BOARD_PHOTO
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO01');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO02');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO03');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO04');
INSERT INTO BOARD_PHOTO (BOARD_PHOTO_NO, BOARD_NO, PHOTO) VALUES (SEQ_BOARD_PHOTO_NO.NEXTVAL, '1', 'PHOTO05');

--REPLY
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '1', '1', '´ë´äÀÌ¿¡¿ä', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '1', '´ë´äÀÌ¿¡¿ä1', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '5', '7', '´ë´äÀÌ¿¡¿ä2', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '7', '´ë´äÀÌ¿¡¿ä3', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '5', '8', '´ë´äÀÌ¿¡¿ä4', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '2', '9', '´ë´äÀÌ¿¡¿ä5', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '4', '2', '´ë´äÀÌ¿¡¿ä6', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '3', '3', '´ë´äÀÌ¿¡¿ä7', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '6', '5', '´ë´äÀÌ¿¡¿ä8', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '7', '2', '´ë´äÀÌ¿¡¿ä9', SYSDATE, SYSDATE, 'O');
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '8', '3', '´ë´äÀÌ¿¡¿ä0', SYSDATE, SYSDATE, 'O');

-- ANSWER
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '¹«ÇÃ¹æÁöÇùÈ¸01', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '¹«ÇÃ¹æÁöÇùÈ¸02', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 3, '¹«ÇÃ¹æÁöÇùÈ¸03', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 3, '¹«ÇÃ¹æÁöÇùÈ¸04', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 5, '¹«ÇÃ¹æÁöÇùÈ¸05', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 6, '¹«ÇÃ¹æÁöÇùÈ¸06', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 7, '¹«ÇÃ¹æÁöÇùÈ¸07', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 2, '¹«ÇÃ¹æÁöÇùÈ¸08', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 2, '¹«ÇÃ¹æÁöÇùÈ¸09', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '¹«ÇÃ¹æÁöÇùÈ¸10', SYSDATE, SYSDATE, 'O', 1);
INSERT INTO ANSWER (ANSWER_NO, REPLY_NO2, ANSWER_CONTENT, ENROLL_DATE, MODIFY_DATE, STATUS, MEMBER_NO) VALUES (SEQ_ANSWER_NO.NEXTVAL, 1, '¹«ÇÃ¹æÁöÇùÈ¸11', SYSDATE, SYSDATE, 'O', 1);

--NOTICE
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', 'ÁýÀÌ¶õ1', 'Áý¿¡º¸³»Áà¿ä1', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ2', 'Áý¿¡º¸³»Áà¿ä2', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ3', 'Áý¿¡º¸³»Áà¿ä3', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ4', 'Áý¿¡º¸³»Áà¿ä4', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ5', 'Áý¿¡º¸³»Áà¿ä5', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ6', 'Áý¿¡º¸³»Áà¿ä6', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ7', 'Áý¿¡º¸³»Áà¿ä7', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ8', 'Áý¿¡º¸³»Áà¿ä8', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ9', 'Áý¿¡º¸³»Áà¿ä9', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ10', 'Áý¿¡º¸³»Áà¿ä10', SYSDATE, SYSDATE, '1', 'O');
INSERT INTO NOTICE(NOTICE_NO, ADMIN_NO, NOTICE_TITLE, NOTICE_CONTENT, ENROLL_DATE, MODIFY_DATE, HIT, STATUS)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, 'ÁýÀÌ¶õ11', 'Áý¿¡º¸³»Áà¿ä11', SYSDATE, SYSDATE, '1', 'O');

--NOTICE_PHOTO
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '1', 'AAA');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '2', 'BBB');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '3', 'CCC');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '4', 'DDD');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '5', 'EEE');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '6', 'FFF');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '7', 'GGG');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '8', 'HHH');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '9', 'III');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '10', 'KKK');
INSERT INTO NOTICE_PHOTO(NOTICE_PHOTO_NO, NOTICE_NO, PHOTO) VALUES(SEQ_NOTICE_PHOTO_NO.NEXTVAL, '11', 'LLL');

--REVIEW
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ1', '¸®ºä ³»¿ë1', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ2', '¸®ºä ³»¿ë2', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ3', '¸®ºä ³»¿ë3', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ4', '¸®ºä ³»¿ë4', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ5', '¸®ºä ³»¿ë5', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ6', '¸®ºä ³»¿ë6', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ7', '¸®ºä ³»¿ë7', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ8', '¸®ºä ³»¿ë8', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ9', '¸®ºä ³»¿ë9', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ10', '¸®ºä ³»¿ë10', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO REVIEW VALUES(SEQ_REVIEW_NO.NEXTVAL, '1', '¸®ºä Á¦¸ñ11', '¸®ºä ³»¿ë11', SYSDATE, SYSDATE, 'AAA', 'O');

--TEAM
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '1Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '2Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '3Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '4Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '5Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '6Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '7Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '8Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '9Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '10Á¶');
INSERT INTO TEAM(TEAM_NO, TEAM_NAME) VALUES(SEQ_TEAM_NO.NEXTVAL, '11Á¶');

--STUDENT
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(1, 1, 1, 0);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(2, 1, 1, 10);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(3, 1, 1, 20);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(4, 1, 2, 30);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(5, 1, 2, 40);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(6, 1, 2, 50);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(7, 2, 1, 60);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(8, 2, 1, 70);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(9, 2, 2, 80);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(10, 2, 2, 90);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(11, 3, 1, 10);
INSERT INTO STUDENT(STUDENT_MEMBER_NO, LECTURE_NO, TEAM_NO, MILEAGE) VALUES(12, 3, 1, 20);

-- ATTENDANCE_LIST
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '1', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '2', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '2', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '2', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '2', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '2', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '3', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '3', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '3', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '3', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '3', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230501, '4', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230502, '4', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230503, '4', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230504, '4', SYSDATE, SYSDATE, 'X');
INSERT INTO ATTENDANCE_LIST (ATTENDANCE_DATE, STUDENT_MEMBER_NO, CHECK_IN_TIME, CHECK_OUT_TIME, STATUS) VALUES (20230505, '4', SYSDATE, SYSDATE, 'X');

--QNA
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'ÀÌ°Å ¾ÈµÇ´Âµ¥', 'ÀÌ°Å ÀÛµ¿ÀÌ ¾ÈµÇ´Âµ¥', 'Àú°Å ÇØº¸¼¼¿ä', SYSDATE, SYSDATE, 'AAA', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', '³ª', 'Èûµé¾î', 'Àúµµ Èûµé¾î¿ä', SYSDATE, SYSDATE, 'BBB', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '1', 'Å¸ÀÌÆ²1', '³»¿ë1', '´ë´ä1', SYSDATE, SYSDATE, 'AAA1', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', 'Å¸ÀÌÆ²2', '³»¿ë2', '´ë´ä2', SYSDATE, SYSDATE, 'AAA2', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', 'Å¸ÀÌÆ²3', '³»¿ë3', '´ë´ä3', SYSDATE, SYSDATE, 'AAA3', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '2', 'Å¸ÀÌÆ²4', '³»¿ë4', '´ë´ä4', SYSDATE, SYSDATE, 'AAA4', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', 'Å¸ÀÌÆ²5', '³»¿ë5', '´ë´ä5', SYSDATE, SYSDATE, 'AAA5', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', 'Å¸ÀÌÆ²6', '³»¿ë6', '´ë´ä6', SYSDATE, SYSDATE, 'AAA6', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '3', 'Å¸ÀÌÆ²7', '³»¿ë7', '´ë´ä7', SYSDATE, SYSDATE, 'AAA7', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '4', 'Å¸ÀÌÆ²8', '³»¿ë8', '´ë´ä8', SYSDATE, SYSDATE, 'AAA8', 'O');
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '4', 'Å¸ÀÌÆ²9', '³»¿ë9', '´ë´ä9', SYSDATE, SYSDATE, 'AAA9', 'O');

--VACATION_REQUEST_LIST
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230202', '20230202', 'O', '°áÈ¥½Ä');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230303', '20230303', 'O', '¿©Çà');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 1, '20230404', '20230404', 'X', 'Á¶ºÎ»ó');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230202', '20230202', 'O', 'ÈÞ½Ä');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230303', '20230303', 'O', 'ÀÔ¿ø');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 2, '20230404', '20230404', 'X', '³ªµéÀÌ');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230202', '20230202', 'O', '¹ß¸ñ ºÎ»ó');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230303', '20230303', 'O', '½Ì½Ì¹Ì¿ª');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 3, '20230404', '20230404', 'X', 'È÷È÷');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230202', '20230202', 'O', 'º´¿ø');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230303', '20230303', 'O', '¸éÁ¢');
INSERT INTO VACATION_REQUEST_LIST(VACATION_REQUEST_LIST_NO, MEMBER_NO, VACATION_START, VACATION_END, STATUS, REASON) VALUES(SEQ_VACATION_REQUEST_LIST_NO.NEXTVAL, 4, '20230404', '20230404', 'O', 'ÇìÇì');

--TEAM_ROLE
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 1, 'Á¶Àå', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 2, 'DB°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 3, 'Çü»ó°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 4, 'ÇÁ·ÐÆ®°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 1, 5, 'ÀÌ½´°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 6, 'Á¶Àå', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 7, 'DB°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 8, 'Çü»ó°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 9, 'ÇÁ·ÐÆ®°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 2, 10, 'ÀÌ½´°ü¸®ÀÚ', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 11, 'Á¶Àå', '¼¼¹Ì');
INSERT INTO TEAM_ROLE(TEAM_ROLE_NO, TEAM_NO, STUDENT_MEMBER_NO, ROLE, PROJECT_DIVISION) VALUES(SEQ_TEAM_ROLE_NO.NEXTVAL, 3, 12, 'DB°ü¸®ÀÚ', '¼¼¹Ì');

--TEAM_CALANDAR
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 1, 20230502, 20230503, '1Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 1, 20230506, 20230507, '¹ã»ù ÄÚµù');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 1, 20230515, 20230517, 'µðºñ ±¸¼º');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 1, 20230523, 20230524, '¹ßÇ¥');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 2, 20230501, 20230502, '1Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 2, 20230601, 20230602, '2Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 2, 20230701, 20230702, '3Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 2, 20230501, 20230502, '¹ßÇ¥');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 3, 20230601, 20230602, '1Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 3, 20230602, 20230603, '2Â÷ È¸ÀÇ');
INSERT INTO TEAM_CALENDAR VALUES(SEQ_TEAM_CALENDAR_NO.NEXTVAL, 3, 20230701, 20230703, '¹ßÇ¥');

COMMIT;
---------------------------
--SELECT * FROM ADMIN;
--SELECT * FROM ANSWER;
--SELECT * FROM ATTENDANCE_LIST;
--SELECT * FROM BOARD;
--SELECT * FROM BOARD_CATEGORY;
--SELECT * FROM BOARD_PHOTO;
--SELECT * FROM EXAM_CATEGORY;
--SELECT * FROM EXAM_LIST;
--SELECT * FROM LECTURE;
--SELECT * FROM LECTURE_CATEGORY;
--SELECT * FROM LETTER;
--SELECT * FROM MEMBER;
--SELECT * FROM NOTICE;
--SELECT * FROM NOTICE_PHOTO;
--SELECT * FROM PROBLEM_BANK;
--SELECT * FROM QNA;
--SELECT * FROM REPLY;
--SELECT * FROM REVIEW;
--SELECT * FROM STUDENT;
--SELECT * FROM SUBMIT_ANSWER;
--SELECT * FROM TEAM;
--SELECT * FROM TEAM_CALENDAR;
--SELECT * FROM TEAM_ROLE;
--SELECT * FROM VACATION_REQUEST_LIST;